# Generated by Django 5.2.5 on 2025-10-04 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestionGroup",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="组ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="组标题")),
                ("description", models.TextField(verbose_name="组描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "题目组",
                "verbose_name_plural": "题目组",
                "db_table": "quiz_question_group",
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="题目ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="题目内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "单选题"),
                            ("multiple", "多选题"),
                            ("single-with-text", "单选带文本"),
                            ("image-single", "图片单选"),
                            ("image-multiple", "图片多选"),
                            ("text", "文本题"),
                        ],
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "image_range",
                    models.JSONField(blank=True, null=True, verbose_name="图片范围"),
                ),
                (
                    "images_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="图片路径"
                    ),
                ),
                (
                    "min_selection",
                    models.IntegerField(default=1, verbose_name="最小选择数"),
                ),
                (
                    "max_selection",
                    models.IntegerField(default=1, verbose_name="最大选择数"),
                ),
                (
                    "show_text_when",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="显示文本条件",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quizquestiongroup",
                        verbose_name="所属组",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "db_table": "quiz_question",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=500, verbose_name="选项文本")),
                ("value", models.CharField(max_length=255, verbose_name="选项值")),
                (
                    "emoji",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="表情符号"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="选项图片"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quiz.quizquestion",
                        verbose_name="所属题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目选项",
                "verbose_name_plural": "题目选项",
                "db_table": "quiz_question_option",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserQuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("abandoned", "已放弃"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="持续时间(毫秒)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户测验会话",
                "verbose_name_plural": "用户测验会话",
                "db_table": "user_quiz_session",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="答案值"),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="文本答案"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="答题时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="quiz.quizquestion",
                        verbose_name="题目",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.userquizsession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户答题记录",
                "verbose_name_plural": "用户答题记录",
                "db_table": "user_answer",
            },
        ),
    ]
