# Generated by Django 5.2.5 on 2025-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FragranceCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="香调ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="中文名称")),
                (
                    "english_name",
                    models.CharField(max_length=100, verbose_name="英文名称"),
                ),
                (
                    "core_trait_1",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="核心特质1(类型/强度)",
                    ),
                ),
                (
                    "core_trait_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="核心特质2(类型/强度)",
                    ),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        default=5, help_text="1-10之间的数值", verbose_name="气味强度"
                    ),
                ),
                (
                    "style_keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="香气风格关键词"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(max_length=255, verbose_name="图片地址"),
                ),
                (
                    "category_type",
                    models.CharField(max_length=50, verbose_name="香调类别"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "香调类别",
                "verbose_name_plural": "香调类别",
                "db_table": "fragrance_category",
            },
        ),
    ]
