# Generated by Django 5.2.5 on 2025-10-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_fragrancecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="part",
            field=models.IntegerField(default=1, verbose_name="所属阶段（1-4）"),
        ),
        migrations.AddField(
            model_name="userquizsession",
            name="current_part",
            field=models.IntegerField(default=1, verbose_name="当前所处阶段（1-4）"),
        ),
    ]
