# Generated by Django 5.2.5 on 2025-10-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fragrancecategory",
            name="intensity",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="气味强度"
            ),
        ),
    ]
