# Generated by Django 5.2.5 on 2025-10-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_fragrancecategory_intensity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fragrancecategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
