# Generated by Django 5.2.5 on 2025-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_useranswer_part_userquizsession_current_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquizsession",
            name="main_fragrance",
            field=models.CharField(blank=True, default="柑橘类", max_length=50, verbose_name="主香调"),
        ),
        migrations.AddField(
            model_name="userquizsession",
            name="secondary_fragrance",
            field=models.CharField(blank=True, default="花卉类", max_length=50, verbose_name="次香调"),
        ),
    ]