# Generated by Django 5.2.5 on 2025-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_fragrancecategory_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquizsession",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="用户情况分析描述"
            ),
        ),
    ]
